import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-black text-white`}>
        <header className="p-6 max-w-7xl mx-auto ">
          <nav className="flex gap-10">
            <Link href="/">Home</Link>
            <Link href="/suspense">With Suspense</Link>
            <Link href="/parallel">With Parallel</Link>
            <Link href="/parallel/test">Teat Route</Link>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
